export const Permission = {
  MANAGE_USERS_ORGANIZATION: "MANAGE_USERS_ORGANIZATION",
  MANAGE_INVITATIONS_ORGANIZATION: "MANAGE_INVITATIONS_ORGANIZATION",
  MANAGE_INVITATIONS_GLOBAL: "MANAGE_INVITATIONS_GLOBAL",
  VIEW_USERS_ORGANIZATION: "VIEW_USERS_ORGANIZATION",
  VIEW_USERS_GLOBAL: "VIEW_USERS_GLOBAL",
  MANAGE_USERS_GLOBAL: "MANAGE_USERS_GLOBAL",
  VIEW_EVENTS_ORGANIZATION: "VIEW_EVENTS_ORGANIZATION",
  MANAGE_EVENTS_ORGANIZATION: "MANAGE_EVENTS_ORGANIZATION",
  VIEW_CUSTOMERS_ORGANIZATION: "VIEW_CUSTOMERS_ORGANIZATION",
  MANAGE_CUSTOMERS_ORGANIZATION: "MANAGE_CUSTOMERS_ORGANIZATION",
  VIEW_INVENTORY_ORGANIZATION: "VIEW_INVENTORY_ORGANIZATION",
  MANAGE_INVENTORY_ORGANIZATION: "MANAGE_INVENTORY_ORGANIZATION",
  VIEW_REPORTS_ORGANIZATION: "VIEW_REPORTS_ORGANIZATION",
  VIEW_ORGANIZATIONS_GLOBAL: "VIEW_ORGANIZATIONS_GLOBAL",
  MANAGE_ORGANIZATIONS_GLOBAL: "MANAGE_ORGANIZATIONS_GLOBAL",
} as const;

export type Permission = typeof Permission[keyof typeof Permission];