export const Permission = {
  MANAGE_USERS_ORGANIZATION: "MANAGE_USERS_ORGANIZATION",
  MANAGE_INVITATIONS_ORGANIZATION: "MANAGE_INVITATIONS_ORGANIZATION",
  MANAGE_INVITATIONS_GLOBAL: "MANAGE_INVITATIONS_GLOBAL",
  VIEW_USERS_ORGANIZATION: "VIEW_USERS_ORGANIZATION",
  VIEW_USERS_GLOBAL: "VIEW_USERS_GLOBAL",
  MANAGE_USERS_GLOBAL: "MANAGE_USERS_GLOBAL",
  // Add other permissions as needed
} as const;

export type Permission = typeof Permission[keyof typeof Permission];